"""empty message

Revision ID: 52651d20698f
Revises: acb55a2dcf10
Create Date: 2019-04-11 10:14:36.292775

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '52651d20698f'
down_revision = 'acb55a2dcf10'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('voke',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('topic_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['topic_id'], ['topic.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.ID'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('voke')
    # ### end Alembic commands ###
